SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

FONT = 'Comic Sans MS'
SCORE_TEXT_SIZE = 50
SCORE_POS_X = SCREEN_WIDTH - 350
SCORE_POS_Y = SCREEN_HEIGHT - 650
SCORE_LARGE = 10
SCORE_MEDIUM = 20
SCORE_SMALL = 50

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

FPS = 60
MS_TO_S = 1000

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SHOT_RADIUS = 5

NEW_ASTEROID_ANGLE_MIN = 20
NEW_ASTEROID_ANGLE_MAX = 50
NEW_ASTEROID_VELOCITY_FACTOR = 1.2